# Loki Multi-Tenant Configuration
# For production environments with multiple tenants/teams
# Requires: auth_enabled: true, X-Scope-OrgID header in all requests

auth_enabled: true  # REQUIRED for multi-tenancy

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  log_format: logfmt
  graceful_shutdown_timeout: 30s

  # HTTP server tuning for multi-tenant workloads
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s

common:
  path_prefix: /loki
  storage:
    s3:
      s3: s3://us-east-1/multi-tenant-loki-bucket
      s3forcepathstyle: false
      # Use IAM roles for authentication (recommended)
  replication_factor: 3
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki-memberlist

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

# Default limits (applied to all tenants)
limits_config:
  # Ingestion limits per tenant
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 40
  max_line_size: 256KB
  max_line_size_truncate: true

  # Stream limits per tenant
  max_streams_per_user: 50000
  max_global_streams_per_user: 100000

  # Query limits per tenant
  max_entries_limit_per_query: 5000
  max_query_length: 721h
  max_query_parallelism: 16
  max_query_series: 500

  # Retention (default for all tenants)
  retention_period: 30d

  # Chunks
  max_chunks_per_query: 2000000

  # Structured metadata
  allow_structured_metadata: true
  max_structured_metadata_size: 64KB
  max_structured_metadata_entries_count: 128

  # Volume API
  volume_enabled: true

  # OTLP Configuration (Loki 3.0+)
  # IMPORTANT: k8s.pod.name and service.instance.id are NOT index labels (high cardinality)
  # See: https://grafana.com/docs/loki/latest/get-started/labels/remove-default-labels/
  otlp_config:
    resource_attributes:
      ignore_defaults: false
      attributes_config:
        - action: index_label
          attributes:
            - service.name
            - service.namespace
            - deployment.environment
        - action: structured_metadata
          attributes:
            - k8s.pod.name         # High cardinality - stored as structured metadata
            - service.instance.id  # High cardinality - stored as structured metadata
    log_attributes:
      - action: structured_metadata
        attributes:
          - trace_id
          - span_id

  # Cardinality limits (important for multi-tenant)
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30

  # Per-stream rate limiting
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB

# Per-tenant overrides (higher limits for specific tenants)
# Reference: https://grafana.com/docs/loki/latest/configure/#runtime-configuration-file
# Create a runtime-config.yaml ConfigMap with:
#
# overrides:
#   # Premium tenant with higher limits
#   tenant-premium:
#     ingestion_rate_mb: 100
#     ingestion_burst_size_mb: 200
#     max_streams_per_user: 200000
#     max_global_streams_per_user: 500000
#     retention_period: 180d
#     max_query_parallelism: 64
#
#   # Standard tenant with default limits
#   tenant-standard:
#     ingestion_rate_mb: 20
#     ingestion_burst_size_mb: 40
#     retention_period: 30d
#
#   # Development tenant with lower limits
#   tenant-dev:
#     ingestion_rate_mb: 5
#     ingestion_burst_size_mb: 10
#     max_streams_per_user: 10000
#     retention_period: 7d

# Runtime configuration for per-tenant overrides
runtime_config:
  file: /etc/loki/runtime-config.yaml
  period: 10s  # How often to reload

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

ingester:
  chunk_encoding: snappy
  chunk_idle_period: 30m
  chunk_retain_period: 15m
  max_chunk_age: 2h
  chunk_target_size: 1572864

  # Lifecycle configuration
  lifecycler:
    ring:
      replication_factor: 3

# Pattern Ingester (Loki 3.0+)
pattern_ingester:
  enabled: true

querier:
  max_concurrent: 8
  query_timeout: 5m

query_frontend:
  # Per-tenant queue limits
  max_outstanding_per_tenant: 2048
  compress_responses: true
  encoding: protobuf

  # Query scheduling
  scheduler_address: ""  # Use embedded scheduler

query_range:
  parallelise_shardable_queries: true
  cache_results: true

  # Split queries for better multi-tenant performance
  split_queries_by_interval: 15m

# Query scheduler for fair tenant scheduling
query_scheduler:
  # Fair scheduling across tenants
  max_outstanding_requests_per_tenant: 100

# Distributor configuration
distributor:
  ring:
    kvstore:
      store: memberlist

# Caching configuration
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 256
      parallelism: 10
    memcached_client:
      host: memcached-chunks.loki.svc.cluster.local
      service: memcached-client
      timeout: 500ms

# Results cache for queries
frontend:
  encoding: protobuf
  # Results caching
  results_cache:
    cache:
      memcached_client:
        host: memcached-results.loki.svc.cluster.local
        service: memcached-client
        timeout: 500ms
        max_idle_conns: 100

# TLS Configuration (recommended for production multi-tenant)
# server:
#   http_tls_config:
#     cert_file: /etc/loki/tls/tls.crt
#     key_file: /etc/loki/tls/tls.key
#   grpc_tls_config:
#     cert_file: /etc/loki/tls/tls.crt
#     key_file: /etc/loki/tls/tls.key

# Index Gateway for improved query performance
index_gateway:
  mode: ring
  ring:
    kvstore:
      store: memberlist