# Dependency Review Workflow Example
# Demonstrates: Dependency scanning, license compliance, vulnerability detection

name: Dependency Review

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write  # For commenting on PRs

jobs:
  dependency-review:
    name: Review Dependencies and Licenses
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on critical and high severity vulnerabilities
          fail-on-severity: high

          # Allow specific licenses (adjust based on your policy)
          allow-licenses: >
            MIT,
            Apache-2.0,
            BSD-2-Clause,
            BSD-3-Clause,
            ISC,
            0BSD

          # Deny specific licenses (adjust based on your policy)
          deny-licenses: >
            GPL-3.0,
            AGPL-3.0,
            LGPL-3.0

          # Fail on scopes (optional)
          # fail-on-scopes: runtime

          # Comment on PR with results (default: true)
          comment-summary-in-pr: always

          # Allow dependencies from specific sources
          # allow-dependencies-licenses: pkg:npm/express@*

      - name: Upload dependency graph
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: dependency-graph
          path: dependency-graph.json
          retention-days: 7
          if-no-files-found: ignore